name: Publish
on:
  # workflow_dispatch:
  push:
    branches:
      - jsr

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish

  publish-ext:
    needs: publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish class-validator
        run: |
          cd ext/class-validator
          npx jsr publish

      - name: Publish jwt
        run: |
          cd ext/jwt
          npx jsr publish

      - name: Publish trpc
        run: |
          cd ext/trpc
          npx jsr publish

      - name: Publish twind
        run: |
          cd ext/twind
          npx jsr publish

      - name: Publish zod
        run: |
          cd ext/zod
          npx jsr publish